import React from "react";
import MyContextUtenteType from "./interface/UtenteInterface";

export const UtenteContext = React.createContext<MyContextUtenteType>({
  A4_03_TabRig_Utenti_id_record: undefined,
  setA4_03_TabRig_Utenti_id_record: () => {},
  A4_03_TabRig_Utenti_M_01_nome: "",
  setA4_03_TabRig_Utenti_M_01_nome: () => {},
  A4_03_TabRig_Utenti_M_02_cognome: "",
  setA4_03_TabRig_Utenti_M_02_cognome: () => {},
  A4_03_TabRig_Utenti_M_03_grado: "",
  setA4_03_TabRig_Utenti_M_03_grado: () => {},
  A4_03_TabRig_Utenti_M_04_matricola: "",
  setA4_03_TabRig_Utenti_M_04_matricola: () => {},
  A4_03_TabRig_Utenti_M_05_nome_utente: "",
  setA4_03_TabRig_Utenti_M_05_nome_utente: () => {},
  A4_03_TabRig_Utenti_M_06_password: "",
  setA4_03_TabRig_Utenti_M_06_password: () => {},
  A4_03_TabRig_Utenti_M_07_attivo: 1,
  setA4_03_TabRig_Utenti_M_07_attivo: () => {},
  A4_03_TabRig_Utenti_M_08_data_ultimo_accesso: "",
  setA4_03_TabRig_Utenti_M_08_data_ultimo_accesso: () => {},
  A4_03_TabRig_Utenti_M_09_ora_ultimo_accesso: "",
  setA4_03_TabRig_Utenti_M_09_ora_ultimo_accesso: () => {},
  A4_03_TabRig_Utenti_M_10_reparto: "",
  setA4_03_TabRig_Utenti_M_10_reparto: () => {},
  A4_03_TabRig_Utenti_M_11_indirizzo: "",
  setA4_03_TabRig_Utenti_M_11_indirizzo: () => {},
  A4_03_TabRig_Utenti_M_12_sn_chiave: "",
  setA4_03_TabRig_Utenti_M_12_sn_chiave: () => {},
  A4_03_TabRig_Utenti_M_13_SMSBook: 0,
  setA4_03_TabRig_Utenti_M_13_SMSBook: () => {},
  A4_03_TabRig_Utenti_M_14_email: "",
  setA4_03_TabRig_Utenti_M_14_email: () => {},
  A4_03_TabRig_Utenti_M_15_telefono_uno: "",
  setA4_03_TabRig_Utenti_M_15_telefono_uno: () => {},
  A4_03_TabRig_Utenti_M_16_telefono_due: "",
  setA4_03_TabRig_Utenti_M_16_telefono_due: () => {},
});
